"""add remember flag to refresh_token

Revision ID: 08e49e735a98
Revises: 7d0840eb12e5
Create Date: 2026-07-15 20:58:20.145745

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '08e49e735a98'
down_revision: str | None = '7d0840eb12e5'
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'refresh_token',
        sa.Column('remember', sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('refresh_token', 'remember')
    # ### end Alembic commands ###
